### ISSUE TITLE
How to enable the Lizmap API on QGIS server

### ISSUE THREAD

**Issue by pizzuga** [3liz/qgis-lizmap-server-plugin#11]
Hello, I couldn't succed to display server information (QGIS Server 3.22.8, Lizmap 3.5.4)

![lizmap2](https://user-images.githubusercontent.com/46919251/179064556-810dd41b-ae8e-438d-8bd7-9c0e23b510b8.png)

This is the list of the plugins installed on the server

![lizmap1](https://user-images.githubusercontent.com/46919251/179065184-f1014564-397f-47d6-8ed1-8e4d6a84266b.png)

I set the environmental variable in the server (Apache2) conf file as:

        FcgidInitialEnv QGIS_PLUGINPATH "/opt/qgis/plugin/"
        FcgidInitialEnv QGIS_SERVER_LIZMAP_REVEAL_SETTINGS=True

(I also tried for QGIS_SERVER_LIZMAP_REVEAL_SETTINGS: ="True", True, "True", 1, =1 but without any luck)

the QGIS Server log seems to address the error to the server rather than Lizmap

        20:11:16 INFO Server[6025]: ******************** New request ***************
        20:11:16 INFO Server[6025]: Request URL: http://qgis.server/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json
        20:11:16 INFO Server[6025]: Environment:
        20:11:16 INFO Server[6025]: ------------------------------------------------
        20:11:16 INFO Server[6025]: SERVER_NAME: qgis.server
        20:11:16 INFO Server[6025]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi/lizmap/server.json
        20:11:16 INFO Server[6025]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
        20:11:16 INFO Server[6025]: PATH_INFO: /lizmap/server.json
        20:11:16 INFO Server[6025]: REMOTE_ADDR: 172.16.1.70
        20:11:16 INFO Server[6025]: SERVER_PORT: 80
        20:11:16 INFO Server[6025]: QUERY_STRING: 
        20:11:16 INFO Server[6025]: REQUEST_METHOD: GET
        20:11:16 INFO Server[6025]: SERVER_PROTOCOL: HTTP/1.1
        20:11:16 INFO Server[6025]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
        20:11:16 INFO Lizmap[6025]: Request headers provided
        20:11:16 INFO Lizmap[6025]: No lizmap user groups in request headers
        20:11:16 INFO WfsOutputExtension[6025]: requestReady ran in 0.0s
        20:11:16 WARNING [6025]: HelloFilter.requestReady
        20:11:16 INFO Server[6025]: TEST_NEW_PARAM:ParamsFilter
        20:11:16 INFO Server[6025]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
        20:11:16 INFO Server[6025]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/lizmap'
        20:11:16 INFO Server[6025]: API Lizmap accepts the URL path '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' 
        20:11:16 INFO Server[6025]: Checking API path /server.json for server.json 
        20:11:16 INFO Server[6025]: API Lizmap: found handler server
        20:11:16 INFO WfsOutputExtension[6025]: responseComplete ran in 0.0s
        20:11:16 CRITICAL Server[6025]: 'NoneType' object has no attribute 'upper'
        20:11:16 INFO Server[6025]: Request finished in 1 ms

but I still think (hope) that I'm making a mistake in setting the environmental variable 
The Lizmap_server plugin seems to work, infact @lizmap_user returns the rigth value when I put it as default value for a field in a QGIS project.
The same configuration is present in other Debian bullseye machines and each one has the same problem. 

By the way, I cannot find any server.json file in the machine, is it correct?

Any hints?

**Comment by Gustry** [comment]
You shouldn't install both plugins "Lizmap" and "Lizmap server". Remove the "Lizmap" one and restart QGIS server.

Why do you want "HelloServer" ? I suspect this plugin to generate your error `'NoneType' object has no attribute 'upper'`

Side note, you can update the "qgis-plugin-manager", there is some new features ;-)

> By the way, I cannot find any server.json file in the machine, is it correct?

This is normal, it's an API, the plugin will handle it.

**Comment by Gustry** [comment]
Please have a look to https://github.com/3liz/qgis-plugin-manager#install-needed-plugins-only-mainly-on-qgis-server if you are Italian, you also don't need "Cadastre" plugin.

**Comment by pizzuga** [comment]
@Gustry Thank you very much! I removed Hello Sever, Cadastre, and lizmap and now it works!
![lizmap3](https://user-images.githubusercontent.com/46919251/180992672-0755f17b-bca4-47cc-87e7-cb94c6c29446.png)

**Comment by aeduard** [comment]
Could you help with some debug to enable Lizmap server plugin? I've also installed Lizmap server plugin beside wfsOutputExtension plugin, and added the QGIS_SERVER_LIZMAP_REVEAL_SETTINGS=True environmental variable to fcgid.conf file. Than restarted Apache.

_You must be ensured that this API http://your.qgis.server.url/lizmap/server.json is protected on your webserver._ I'm not sure what is my qgis server url? It is the same address which I'm using to access my lizmap interface? If so, than I get a 404 Not Found error, when trying to access simply from browser.

Bellow you can find the relevant part of the qgis server error log. 

02:35:38 INFO Server[1572]: ******************** New request ***************
02:35:38 INFO Server[1572]: Request URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json
02:35:38 INFO Server[1572]: Environment:
02:35:38 INFO Server[1572]: ------------------------------------------------
02:35:38 INFO Server[1572]: SERVER_NAME: 127.0.0.1
02:35:38 INFO Server[1572]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi/lizmap/server.json
02:35:38 INFO Server[1572]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
02:35:38 INFO Server[1572]: PATH_INFO: /lizmap/server.json
02:35:38 INFO Server[1572]: REMOTE_ADDR: 127.0.0.1
02:35:38 INFO Server[1572]: SERVER_PORT: 80
02:35:38 INFO Server[1572]: QUERY_STRING: 
02:35:38 INFO Server[1572]: REQUEST_METHOD: GET
02:35:38 INFO Server[1572]: SERVER_PROTOCOL: HTTP/1.1
02:35:38 INFO Server[1572]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
02:35:38 INFO Lizmap[1572]: Request headers provided
02:35:38 INFO Lizmap[1572]: No lizmap user groups in request headers
02:35:38 INFO WfsOutputExtension[1572]: WfsOutputExtension.requestReady
02:35:38 INFO Server[1572]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
02:35:38 INFO Server[1572]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/wfs3'
02:35:38 INFO Server[1572]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/'
02:35:38 INFO Server[1572]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/lizmap'
02:35:38 INFO Server[1572]: API Lizmap accepts the URL path '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' 
02:35:38 INFO Server[1572]: Checking API path /server.json for server.json 
02:35:38 INFO Server[1572]: API Lizmap: found handler server
02:35:38 CRITICAL Lizmap[1572]: Please read the documentation how to enable the Lizmap API on QGIS server side https://docs.lizmap.com/current/en/install/pre_requirements.html#lizmap-server-plugin An environment variable must be enabled to have Lizmap Web Client â‰¥ 3.5.
02:35:38 CRITICAL Lizmap[1572]: Lizmap request error Bad request error: Invalid request
02:35:38 WARNING Server[1572]: [{"code":"Bad request error","description":"Invalid request"}]
02:35:38 INFO WfsOutputExtension[1572]: WfsOutputExtension.responseComplete
02:35:38 INFO Server[1572]: Request finished in 0 ms

**Comment by pizzuga** [comment]
@aeduard 

try **FcgidInitialEnv QGIS_SERVER_LIZMAP_REVEAL_SETTINGS "True"** (FcgidInitialEnv _space_ QGIS_SERVER_LIZMAP_REVEAL_SETTINGS _space double quotes_ True double _quotes_)

I just maked a try (Debian and Apache server) and it dosen't work if I put the sentence like the one written in the documentation

**Comment by Gustry** [comment]
If you don't restart QGIS server, the plugin might not be reloaded as well with the new version.
The way to restart QGIS server depends which QGIS server you installed it and how. (docker, supervisor, systemd, servicectl, py-qgis-server or fcgi ...). There isn't a single answer.

**Comment by aeduard** [comment]
I did restart with rebooting the system :). I have fcgi, and qgis server 3.22.9.

**Comment by Gustry** [comment]
With FCGI, you still have a few ways to start QGIS server : systemd, supervisor etc
