### ISSUE TITLE
extension lizmap server

### ISSUE THREAD

**Issue by geografic2b** [3liz/qgis-lizmap-server-plugin#14]
## Description
Comment installer le plugin lizmap server ?
Sur le serveur j'ai cette variable : FcgidInitialEnv QGIS_PLUGINPATH "/home/pif/www/qgis-server/plugins"
Et dans le repertoire plugin j'ai copié le plugin lizmap server.
Malgré ça, dans le panneau d'administration de lizmap j'ai ce message 
"QGIS Serveur est correctement installé et retourne une réponse attendue pour les requêtes OGC.

Nous ne pouvons avoir les détails sur l'installation de votre serveur QGIS (version, extensions etc.).
Soit la version installée du serveur QGIS est inférieure à 3.10, soit le plugin Lizmap n'est pas installé sur votre serveur, ou installé avec une version inférieur à 3.7.0. Mettez à jour QGIS Serveur au minimum à la version 3.10, et installez ou mettez à jour l'extension Lizmap à la version 3.7.0 minimum, en lisant la documentation https://docs.lizmap.com/current/fr/install/pre_requirements.html.
QGIS Serveur retourne une erreur HTTP à propos de l'extension Lizmap : 500"

J'ai forcément oublié une étape.

Merci d'avance pour votre aide.

## Context
* QGIS version:  3.10
* Lizmap version: 3.5 
* OS:  unbuntu
![image](https://user-images.githubusercontent.com/76677832/184658760-48d8c701-e814-47f1-bfb5-8fbef2339a12.png)

**Comment by Gustry** [comment]
https://docs.lizmap.com/current/fr/install/pre_requirements.html#qgis-server-side
Avez-vous lu la documentation sur la variable d'environnement ?

**Comment by geografic2b** [comment]
oui, je ne comprends pas tout  et c'est l'objet de ma question.
"La variable d'environnement doit être définie dans QGIS Server. Le nom du plugin est Lizmap server ."
Pour répondre à cette spécification, j'ai donc copié le plugin lizmap server dans le répertoire plugins
et j'ai déclaré cette variable FcgidInitialEnv QGIS_PLUGINPATH "/home/pif/www/qgis-server/plugins".

**Comment by Gustry** [comment]
Désolé, je ne parle pas de la variable d'environnement `QGIS_PLUGINPATH`.
As tu clique sur le lien ci dessus et lu l'encadré orange ? Ça parle de la variable d'environnement qu'il faut utiliser.

Dans les logs de QGIS serveur, il doit aussi y avoir marqué ce qu'il ne marche pas.

**Comment by Gustry** [comment]
https://docs.qgis.org/3.22/en/docs/server_manual/config.html#id1 Pour les logs dans QGIS serveur

**Comment by geografic2b** [comment]
J'ai paramétré ceci :
FcgidInitialEnv QGIS_PLUGINPATH "/home/pif/www/qgis-server/plugins"
FcgidInitialEnv QGIS_SERVER_LOG_STDERR "1"
FcgidInitialEnv QGIS_SERVER_LIZMAP_REVEAL_SETTINGS="True"

**Comment by geografic2b** [comment]
FcgidInitialEnv QGIS_SERVER_LOG_STDERR 1 
FcgidInitialEnv QGIS_SERVER_LOG_FILE "home/pif/www/qgis-server/plugins/qgisserver.log"
cette n=instruction est obsoléte si version > 3.4 à priori
alors comment indiquer l'emplacement du log ?

**Comment by Gustry** [comment]
L'ajout de la variable Lizmap ne suffit pas ? Est ce que tu as redémarrer ton qgis serveur ?
Pour les logs, je ne peux pas t'aider, il faut comprendre ce qu'est STDERR car ce n'est pas un fichier. Personnellement j'utilise `journalctl`. Mais cela dépend de comment tu installes qgis serveur. Si tu ne sais pas, le plus simple est d'utiliser log file alors.

**Comment by Gustry** [comment]
Sans plus d'information, je ne peux pas vraiment aider.
Contenu du répertoire ? droits sur le répertoire ?
Bonne extension "Lizmap serveur" ?

L'astuce peut aider, en vert, utilisation de qgis-plugin-manager https://docs.lizmap.com/current/fr/install/pre_requirements.html#qgis-server-plugins

https://docs.lizmap.com/current/fr/install/pre_requirements.html#installation

> l'extension Lizmap à la version 3.7.0 

Comme dit dans un précédent ticket, ceci n'est désormais plus vrai. Il faut regarder la documentation concernant le plugin "lizmap server".

**Comment by geografic2b** [comment]
Voici le repertoire. 
Et ensuite je ne vois pas comment exécuter ces instructions et en particulier "installer"
pip3 installer qgis-plugin-manager             
python3 -m pip installe le gestionnaire de plugins qgis

**Comment by geografic2b** [comment]
J'ai reussi à l'installer ! voilà le message.
|  Dossier ⬇ |  Nom |  Version |  Drapeaux |  QGIS min |  QGIS maximum |  Auteur |  Droits de dossier |  Action ⚠ | 
------------------------------------------------------------------------------------------------------------------------------------                                                           
|  Serveur Lizmap |Serveur Lizmap |1.1.1 |Serveur |3.10 |3.99 |3Liz |pif : 0o775 |Version inconnue| 
|wfsOutputExtension|wfsOutputExtension|v1.5.3 |Serveur |3.0 |  |3Liz |pif : 0o775 |Version inconnue|

**Comment by geografic2b** [comment]
et donc je ne m'explique pas le message :
QGIS Serveur est correctement installé et retourne une réponse attendue pour les requêtes OGC.

Nous ne pouvons avoir les détails sur l'installation de votre serveur QGIS (version, extensions etc.).
Soit la version installée du serveur QGIS est inférieure à 3.10, soit le plugin Lizmap n'est pas installé sur votre serveur, ou installé avec une version inférieur à 3.7.0. Mettez à jour QGIS Serveur au minimum à la version 3.10, et installez ou mettez à jour l'extension Lizmap à la version 3.7.0 minimum, en lisant la documentation https://docs.lizmap.com/current/fr/install/pre_requirements.html.
QGIS Serveur retourne une erreur HTTP à propos de l'extension Lizmap : 500

**Comment by Gustry** [comment]
Tu peux renommer `Serveur Lizmap` en `lizmap_server` ?
et redémarrer le serveur QGIS.
Il faut lire les logs de QGIS il y a peut-être des informations.

Je ne comprends pas pourquoi il y a autant de message en français dans ton tableau des extensions QGIS. C'est outil n'est pas traduit en français.

**Comment by geografic2b** [comment]
J'ai renommer  en lizmap_server et même message, bizarre, non ?
j'ai ajouté ça :
FcgidInitialEnv QGIS_SERVER_LOG_FILE "home/pif/www/qgis-server/plugins/qgisserver.log"
et pas de logs...

**Comment by geografic2b** [comment]
![im](https://user-images.githubusercontent.com/76677832/188129008-6f540bd7-d17c-4ab9-8f8d-9eb8fbe13eec.jpg)

**Comment by geografic2b** [comment]
si ça peut aider...

**Comment by Gustry** [comment]
```
 FcgidInitialEnv QGIS_SERVER_LOG_FILE "home/pif/www/qgis-server/plugins/qgisserver.log"
```

Votre chemin n'est pas correct ...
Essayer de faire un `touch home/pif/www/qgis-server/plugins/qgisserver.log`, vous allez avoir une erreur.

**Comment by geografic2b** [comment]
Bonjour,
J'ai toujours le même message même en corrigeant.
dans le log de lizmap j'ai ça 
022-09-12 17:27:05	2a01:cb1c:fb1:9f00:95dd:9ad5:15ab:cc44	warning	2022-09-12 17:27:05	[2]	chmod(): No such file or directory	/home/oxygeme/www/lib/jelix/utils/jFile.class.php	102

2022-09-12 17:27:05	2a01:cb1c:fb1:9f00:95dd:9ad5:15ab:cc44	warning	2022-09-12 17:27:05	[2]	mkdir(): No such file or directory	/home/oxygeme/www/lib/jelix/utils/jFile.class.php	99

2022-09-12 17:27:05	2a01:cb1c:fb1:9f00:95dd:9ad5:15ab:cc44	warning	2022-09-12 17:27:05	[2]	chmod(): No such file or directory	/home/oxygeme/www/lib/jelix/utils/jFile.class.php	102

**Comment by geografic2b** [comment]
Par ailleurs, j'aimerai changer le message "Click features on the map to access edition tools" par un message en français en mode édition. Je n'ai pas trouvé dans le dictionnaire. ça se trouve où ?
