### ISSUE TITLE
Lizmap et le navigateur Safari

### ISSUE THREAD

**Issue by geografic2b** [3liz/qgis-lizmap-server-plugin#18]
Une appplication fonctionne très bien sur mozilla alors que l'affichage des forumulaires est décalée sur Safari. ?

**Comment by Gustry** [comment]
Bonjour,

Vous êtes sur le dépôt GitHub [qgis-lizmap-server-plugin](https://github.com/3liz/qgis-lizmap-server-plugin) qui est une extension Python pour QGIS serveur. Il faut créer votre ticket sur l'application Lizmap Web Client. Il faudra aussi fournir des captures d'écran, des informations complémentaires, le type de formulaire etc, sinon, il est impossible de debugger.
