### ISSUE TITLE
Use the image Py-QGIS-Server for testing

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-lizmap-server-plugin#2]
For now, it's using 3liz/qgis-platform.

From @dmarteau in 3liz/lizmap-plugin#395 :  

> You should use test workflow as used in https://github.com/3liz/qgis-server-wmts-cache-plugin/tree/master/tests

What you be the benefits compare to qgis-platform ?

**Comment by dmarteau** [comment]
> What you be the benefits compare to qgis-platform 

Afaik, the tests use qgis-platform https://github.com/3liz/qgis-server-wmts-cache-plugin/blob/master/Makefile#L20 and not py-qgis-server. 

The docker-compose.yml  https://github.com/3liz/qgis-server-wmts-cache-plugin/tree/master/tests is just here for conveniently start a qgis server with the plugin loaded.

**Comment by dmarteau** [comment]
I'm not sure that this issue is relevant since the tests already use the same workflow as  https://github.com/3liz/qgis-server-wmts-cache-plugin/tree/master/tests.

**Comment by Gustry** [comment]
I though WMTS use Py-QGIS-Server from the docker-compose file : https://github.com/3liz/qgis-server-wmts-cache-plugin/blob/master/tests/docker-compose.yml#L4
What is the different with the Makefile ?

**Comment by dmarteau** [comment]
> I though WMTS use Py-QGIS-Server from the docker-compose file : https://github.com/3liz/qgis-server-wmts-cache-plugin
As I said before, the docker-compose file is just here for convenience, not related to tests.

> What is the different with the Makefile ?

Different from what ?

**Comment by Gustry** [comment]
ok sorry, understood.
It's alright so !
