### ISSUE TITLE
Provide py-qgis-server version in the JSON file

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-lizmap-server-plugin#3]
If the server is running py-qgis-server, we could add its version in the JSON file.
So then, for admins, this version can be displayed in the LWC admin panel, same as QGIS Server version etc to be able to track more easily the LWC environment.

CC @dmarteau

**Comment by dmarteau** [comment]
Basically plugins are agnostic with respect to the kind of server used:  you will have to try an 'import pyqgissever', so there is no clean generic solution.

Amha, is much better to rely on  the 'Server' header on client side.
