### ISSUE TITLE
Error with server metadata on 1.3.0

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-lizmap-server-plugin#32]
From @ygorigor on https://github.com/3liz/qgis-lizmap-server-plugin/commit/0e4865d46c2ab2ccad999b8dbfbb30f23df1333a

With this version I have some errors in LWC Server Information

![image](https://user-images.githubusercontent.com/1684359/214577925-3076eed7-0c4f-465d-ab46-b1cd2ddceb7b.png)

With 1.2.2 it's OK

![image](https://user-images.githubusercontent.com/1684359/214578060-82979f5f-402d-4122-ba1a-42a32e752b74.png)

**Comment by Gustry** [comment]
Better to create a ticket.

Can you clarify, so you are areally using Py-QGIS-Server right ?

**Comment by ygorigor** [comment]
> Better to create a ticket.
> 
> Can you clarify, so you are areally using Py-QGIS-Server right ?

Yes, I use Py-QGIS-Server, but when I update server plugin to 1.3.0 it is not detected in LWC anymore.

**Comment by ygorigor** [comment]
Thank you @Gustry. I will check tomorrow
